# Generated by Django 5.2.4 on 2025-11-04 15:27

import django.contrib.auth.validators
import django.core.validators
import django_countries.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="movie_country",
        ),
        migrations.RemoveField(
            model_name="favorite",
            name="user",
        ),
        migrations.RemoveField(
            model_name="favoritemovie",
            name="favorite",
        ),
        migrations.RenameField(
            model_name="actor",
            old_name="actor_bio",
            new_name="bio",
        ),
        migrations.RenameField(
            model_name="actor",
            old_name="actor_name",
            new_name="full_name",
        ),
        migrations.RenameField(
            model_name="actor",
            old_name="actor_image",
            new_name="image",
        ),
        migrations.RemoveField(
            model_name="actor",
            name="actor_age",
        ),
        migrations.RemoveField(
            model_name="actor",
            name="actor_bio_en",
        ),
        migrations.RemoveField(
            model_name="actor",
            name="actor_bio_ru",
        ),
        migrations.RemoveField(
            model_name="actor",
            name="actor_name_en",
        ),
        migrations.RemoveField(
            model_name="actor",
            name="actor_name_ru",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="age",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="history",
            name="user",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="movie_name_en",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="movie_name_ru",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="movie_status",
        ),
        migrations.RemoveField(
            model_name="rating",
            name="user",
        ),
        migrations.AddField(
            model_name="actor",
            name="age",
            field=models.PositiveSmallIntegerField(
                default=18,
                validators=[
                    django.core.validators.MinValueValidator(18),
                    django.core.validators.MaxValueValidator(60),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="actor",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="token",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="data_registered",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="email address"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="status",
            field=models.CharField(
                choices=[("Guest", "Guest"), ("Author", "Author")], default="Guest"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=150,
                unique=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="username",
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="movie_date",
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name="Country",
        ),
        migrations.AddField(
            model_name="movie",
            name="movie_country",
            field=django_countries.fields.CountryField(default=30, max_length=2),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Favorite",
        ),
    ]
