# Generated by Django 5.2.4 on 2025-11-04 15:59

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0002_remove_movie_movie_country_remove_favorite_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="movie_country",
            field=django_countries.fields.CountryField(
                default="Kyrgyzstan", max_length=2
            ),
        ),
    ]
